# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            concertman
tagline:
url:              http://concertman.github.io
paginate:         1
baseurl:          /
author:
  name:           Jarod McBride
  url:            https://twitter.com/concertman
  email:          concertman@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/concertman
